FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# sprint-engine

Sprint engine is an API for a project management system.


## Tasks [/tasks]

### List All Tasks [GET]

Lists all of the tasks.

+ Response 200 (application/json)

        [
            {
                "name": "foo name",
                "description": "bar description",
                "priority": "high",
                "user": {
                    "id": 1,
                    "first_name": "Tyler",
                    "last_name": "Souza",
                    "username": "tysweezy"
                }
            }
        ]


### Create a New Task [POST]

You can create a new task. It takes a JSON payload via a POST request.

+ Request (application/json)

        {
                "name": "foo name",
                "description": "bar description",
                "priority": "high"
        }

+ Response 201 (application/json)

    + Headers

            Location: /tasks/2

    + Body

            {
                "id": 2
                "name": "foo name",
                "description": "bar description",
                "priority": "high",
                "published_at": "2015-08-05T08:40:51.620Z"
 
            }
            
## Task Detail [/tasks/{task_id}]            
            
### Get task detail [GET]

In this endpoint, you can view the details of a particular task.

+ Response 201 (application/json)
    
    + Headers
        
            Location: /tasks/2
        
    + Body
        
            {
                "id": 2
                "name": "foo name",
                "description": "bar description",
                "priority": "high",
                "published_at": "2015-08-05T08:40:51.620Z"
            }

### Update a task [PUT]

You can update the tasks here.

+ Request (application/json)

            {
                "id": 2
                "name": "foo name",
                "description": "bar description",
                "priority": "high",
                "published_at": "2015-08-05T08:40:51.620Z"
            }

+ Response 201 (application/json)
    
    + Headers
        
            Location: /tasks/2
        
    + Body
        
            {
                "id": 2
                "name": "foo name",
                "description": "bar description",
                "priority": "high",
                "published_at": "2015-08-05T08:40:51.620Z"
            }
            
            
### Delete a task [DELETE]

You can delete a task here

+ Request (application/json)

            {
                "id": 2
                "name": "foo name",
                "description": "bar description",
                "priority": "high",
                "published_at": "2015-08-05T08:40:51.620Z"
            }

+ Response 201 (application/json)
    
    + Headers
        
            Location: /tasks/2
        
    + Body
        
            {
                "id": 2
                "name": "foo name",
                "description": "bar description",
                "priority": "high",
                "published_at": "2015-08-05T08:40:51.620Z"
            }